// <auto-generated />
namespace Planner.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class passenger_update_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passenger_update_3));
        
        string IMigrationMetadata.Id
        {
            get { return "202012172226265_passenger_update_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
