// <auto-generated />
namespace Planner.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class route_passenger_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(route_passenger_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202012231726538_route_passenger_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
