// <auto-generated />
namespace Planner.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_owner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_owner));
        
        string IMigrationMetadata.Id
        {
            get { return "202101122209164_add_owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
